# Please update the cartopy, test data, and sample data git references
# below if appropriate.
#
# Note: Contrary to the travis documentation,
# http://about.travis-ci.org/docs/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
# we will use conda to give us a much faster setup time.


language: python
python:
  - 2.7

git:
  depth: 10000

install:
  - export IRIS_TEST_DATA_REF="3378fe68c00ca7f31895ab6630a59a39ccef94e3"
  - export IRIS_TEST_DATA_SUFFIX=$(echo "${IRIS_TEST_DATA_REF}" | sed "s/^v//")

  - export IRIS_SAMPLE_DATA_REF="1ed3e26606366717e2053bacc12bf5e8d8fa2704"
  - export IRIS_SAMPLE_DATA_SUFFIX=$(echo "${IRIS_SAMPLE_DATA_REF}" | sed "s/^v//")

  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget ${CONDA_BASE}-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda update conda
  - ENV_NAME='test-environment'
  - conda create -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

  # Customise the testing environment
  # ---------------------------------
  - conda config --add channels scitools
  # Start with all the mandatory dependencies
  - conda install biggus
  - conda install cartopy matplotlib=1.3.1
  - conda install netcdf4
  - conda install numpy
  - conda install pyke
  - conda install udunits=2
  # Iris build dependencies
  - conda install setuptools
  # Iris testing/documentation dependencies
  - conda install cfchecker
  - conda install mock
  - conda install nose
  - conda install pep8
  - conda install sphinx
  # Optional iris dependencies
  - conda install ecmwf_grib=1.9.16
  - conda install gdal
  - conda install libmo_unpack
  - conda install pandas=0.12.0

  - PREFIX=$HOME/miniconda/envs/$ENV_NAME

  # cfchecker
  - echo '#!/usr/bin/env sh' > cfchecker
  - echo "cfchecks -s `pwd`/etc/cf-standard-name-table.xml -a `pwd`/etc/area-type-table.xml -u $PREFIX/share/udunits/udunits2.xml -v auto \$1" >> cfchecker
  - cp cfchecker $PREFIX/bin/cfchecker
  - chmod a+x $PREFIX/bin/cfchecker

  # Output debug info
  - conda list
  - conda info -a

# Pre-load Natural Earth data to avoid multiple, overlapping downloads.
# i.e. There should be no DownloadWarning reports in the log.
  - python -c 'import cartopy; cartopy.io.shapereader.natural_earth()'

# iris test data
  - wget -O iris-test-data.zip https://github.com/SciTools/iris-test-data/archive/${IRIS_TEST_DATA_REF}.zip
  - unzip -q iris-test-data.zip
  - ln -s $(pwd)/iris-test-data-${IRIS_TEST_DATA_SUFFIX} iris-test-data

# iris sample data
  - wget -O iris-sample-data.zip https://github.com/SciTools/iris-sample-data/archive/${IRIS_SAMPLE_DATA_REF}.zip
  - unzip -q iris-sample-data.zip
  - ln -s $(pwd)/iris-sample-data-${IRIS_SAMPLE_DATA_SUFFIX} iris-sample-data
  
# prepare iris build directory
  - python setup.py --with-unpack build_ext --include-dirs=${PREFIX}/include --library-dirs=${PREFIX}/lib
  - IRIS=$(ls -d1 build/lib*/iris)
  - mkdir $IRIS/etc

# set config paths
  - SITE_CFG=$IRIS/etc/site.cfg
  - echo "[Resources]" > $SITE_CFG
  - echo "sample_data_dir = $(pwd)/iris-sample-data/sample_data" >> $SITE_CFG
  - echo "test_data_dir = $(pwd)/iris-test-data/test_data" >> $SITE_CFG
  - echo "doc_dir = $(pwd)/docs/iris" >> $SITE_CFG
  - echo "[System]" >> $SITE_CFG
  - echo "udunits2_path = $PREFIX/lib/libudunits2.so" >> $SITE_CFG

# iris
  - python setup.py --with-unpack build
  - python setup.py --with-unpack install

script:
  - python -m iris.tests.runner --example-tests

  - cd $(pwd)/docs/iris
# Make html produces an error when run on Travis that does not affect any downstream functionality but causes the build to fail spuriously.
# The following gets around this error, which should be investigated further in the future.
  - echo `make clean html`

  - make doctest
