# Please update the cartopy, test data, and sample data git references below if appropriate.


language: python
python:
  - 2.7

git:
  depth: 0

install:

  - export BIGGUS_REF="da8f19f197adff77e8071b0e04269c8b888a1fbf"
  - export BIGGUS_SUFFIX=$(echo "${BIGGUS_REF}" | sed "s/^v//")

  - export CARTOPY_REF="v0.10.0"
  - export CARTOPY_SUFFIX=$(echo "${CARTOPY_REF}" | sed "s/^v//")

  - export IRIS_TEST_DATA_REF="3378fe68c00ca7f31895ab6630a59a39ccef94e3"
  - export IRIS_TEST_DATA_SUFFIX=$(echo "${IRIS_TEST_DATA_REF}" | sed "s/^v//")

  - export IRIS_SAMPLE_DATA_REF="2e7c73504e3d675d97dc8a2c2939f9fd2cfe51f1"
  - export IRIS_SAMPLE_DATA_SUFFIX=$(echo "${IRIS_SAMPLE_DATA_REF}" | sed "s/^v//")

  - deactivate
# libjpeg62 Dependency of pillow (PIL) - not on ubuntu by default on +12.04
  - sudo apt-get install libjpeg62
  - sudo apt-get install graphviz libjpeg62
  - wget http://repo.continuum.io/miniconda/Miniconda-3.3.0-Linux-x86_64.sh
  - chmod +x Miniconda-3.3.0-Linux-x86_64.sh
  - ./Miniconda-3.3.0-Linux-x86_64.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda create --yes -n test_env -c nbren12 numpy=1.7.1 scipy=0.13.2 matplotlib=1.3.0 netcdf4=1.0.7 scipy=0.13.2
  - source activate test_env
  - conda install --yes -c nbren12 setuptools nose pep8 pyshp shapely udunits2 proj4 pyke geos cython mock sphinx gdal pillow


# grib api - build from source for now
  - sudo apt-get install libjasper-dev
  - sudo apt-get build-dep libgrib-api-1.9.9 libgrib-api-dev libgrib-api-tools
  - wget https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.9.16.tar.gz --no-check-certificate
  - tar -xvf grib_api-1.9.16.tar.gz
  - ln -s ${PWD}/grib_api-1.9.16 grib_api
  - cd grib_api
  - CFLAGS="-fPIC" ./configure --with-jasper=/usr/local/lib --disable-fortran --enable-python
  - make
  - sudo make install
  - cd python
  - python setup.py install
  - cd ../..

# biggus
  - wget -O biggus.zip https://github.com/SciTools/biggus/archive/${BIGGUS_REF}.zip
  - unzip -q biggus.zip
  - ln -s ${PWD}/biggus-${BIGGUS_SUFFIX} biggus
  - cd biggus
  - python setup.py install --user
  - cd ..

# cartopy
  - wget -O cartopy.zip https://github.com/SciTools/cartopy/archive/${CARTOPY_REF}.zip
  - unzip -q cartopy.zip
  - ln -s ${PWD}/cartopy-${CARTOPY_SUFFIX} cartopy
  - cd cartopy
  - python setup.py install --user
  - cd ..

# Pre-load Natural Earth data to avoid multiple, overlapping downloads.
# i.e. There should be no DownloadWarning reports in the log.
  - python -c 'import cartopy; cartopy.io.shapereader.natural_earth()'

# mo_unpack
  - wget https://puma.nerc.ac.uk/trac/UM_TOOLS/raw-attachment/wiki/unpack/unpack-030712.tgz
  - tar -xf unpack-030712.tgz
  - cd unpack-030712/libmo_unpack
#?  - gcc -c -fPIC -O4 -mfpmath=sse -msse -I include -D_LARGEFILE_SOURCE -D_LARGEFILE_SOURCE64 -D_FILE_OFFSET_BITS=64 *.c
  - gcc -c -fPIC -O4 -mfpmath=sse -msse -I include -D_LARGEFILE_SOURCE *.c
  - gcc -shared -Wl,-soname,libmo_unpack.so -o lib/libmo_unpack.so *.o
  - sudo cp lib/* /usr/local/lib
  - sudo cp include/* /usr/local/include
  - cd ../..

# iris test data
  - wget -O iris-test-data.zip https://github.com/SciTools/iris-test-data/archive/${IRIS_TEST_DATA_REF}.zip
  - unzip -q iris-test-data.zip
  - ln -s ${PWD}/iris-test-data-${IRIS_TEST_DATA_SUFFIX} iris-test-data

# iris sample data
  - wget -O iris-sample-data.zip https://github.com/SciTools/iris-sample-data/archive/${IRIS_SAMPLE_DATA_REF}.zip
  - unzip -q iris-sample-data.zip
  - ln -s ${PWD}/iris-sample-data-${IRIS_SAMPLE_DATA_SUFFIX} iris-sample-data

  - export UDUNITS2_XML_PATH=/home/travis/miniconda/envs/test_env/share/udunits/udunits2.xml
  
# iris
  - python setup.py --with-unpack build_ext --inplace -I/usr/local/include -L/usr/local/lib -R/usr/local/lib
  - python setup.py std_names
  - echo "[System]" > lib/iris/etc/site.cfg
  - echo "udunits2_path = /home/travis/miniconda/envs/test_env/lib/libudunits2.so" >> lib/iris/etc/site.cfg
  - echo "dot_path = /usr/bin/dot" >> lib/iris/etc/site.cfg
  - echo "[Resources]" >> lib/iris/etc/site.cfg
  - echo "sample_data_dir = ${PWD}/iris-sample-data/sample_data" >> lib/iris/etc/site.cfg
  - echo "test_data_dir = ${PWD}/iris-test-data/test_data" >> lib/iris/etc/site.cfg
  - ln -s ${PWD}/lib/iris /home/travis/.local/lib/python2.7/site-packages/iris
  - python setup.py pyke_rules

script:
  - python setup.py test --example-tests

  - cd docs/iris
# Make html produces an error when run on Travis that does not affect any downstream functionality but causes the build to fail spuriously.
# The following gets around this error, which should be investigated further in the future.
  - echo `make clean html`

  - make doctest
